let age=22
// we can convert the age in string, boolean like this....

let isString= String(age)                   // it will convert age(a number) to a string...
console.log(isString)                       // it will print 22
console.log(typeof(isString));              // but data type will be string.....


let isBoolean= Boolean(age)                   // it will convert age(a number) to a Boolean...
console.log(isBoolean)                       // it will print true(as there somthing is present)
console.log(typeof(isBoolean));              // but data type will be Boolean.....



let name="Shaon"
// we can convert the name in Number, boolean like this....

let isNumber= Number(name)                   // it will convert name(a string) to a number...
console.log(isNumber)                       // it will print NaN(Not a Number)
console.log(typeof(isNumber));              // but data type will be number.....


let isBool= Boolean(age)                   // it will convert name(a string) to a Boolean...
console.log(isBool)                       // it will print true(as there somthing is present)
console.log(typeof(isBool));              // but data type will be Boolean.....




let flag=true